name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Check Flutter version
        run: flutter --version

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign
